name: agora
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  http:
  html:
  json_annotation:
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  dots_indicator: ^3.0.0
  intl:
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  fluttertoast: ^8.2.5
  auto_route: ^7.2.0
  cupertino_icons: ^1.0.2
  flutter_chat_bubble: ^2.0.2
  calendar_date_picker2: ^1.1.5
  record: ^4.0.0
  openapi:
    path: ./quiz-auth
  questions:
    path: ./questions
  shared_preferences: ^2.2.3
  built_value: ^8.1.3
  built_collection: ^5.1.1
  pretty_dio_logger: ^1.4.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^10.0.0
  web_socket_channel: ^2.4.0
  hex: ^0.2.0
  questions_live:
    path: ./questions-live
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  build_runner:
  json_serializable:
  auto_route_generator: ^7.1.1
  flutter_chat_bubble:
  flutter_lints: ^2.0.0
  material_design_icons_flutter:
  image_picker: 0.8.9
  built_value_generator: ^8.1.3



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/